services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    image: my-client:latest
    networks:
      - app-network
    command: [ "java", "-cp", "out", "client.Client", "server", "9259", "server", "9258" ]
networks:
  app-network:
    driver: bridge